const express = require('express')
const mongo = require('mongoose')
const app = express()
app.use(express.json())
const cors = require('cors');
app.use(cors({
    credentials: true, // Enable cookies and authentication headers
  }));
require('dotenv/config')

const Portfolio = require('./Router/PostPortfolio')
const getPortfolio = require('./Router/GetPortfolio')
const Post = require('./Router/Post')
const Get = require('./Router/Get')
const Mail = require('./Router/Fead')
const Signup = require('./User/Register')
const Login = require('./User/Login')
const PostSkill=require('./Skill/PostSkill')
const GetSkill=require('./Skill/GetSkill')
const DeleteSkill=require('./Skill/DeleteSkill')
const PostInfo=require('./Info/PostInfo')
const GetInfo=require('./Info/GetInfo')
const DeleteInfo=require('./Info/DeleteInfo')
const DeletePortfolio=require('./Router/DeletePortfolio')
const Detail=require('./Router/GetDetail')
const GetContent=require('./Content/GetContent')
const EditContent=require('./Content/EditContent')
const PostContent=require('./Content/PostContent')
const DeleteContent=require('./Content/DeleteContent')
const Related=require('./Router/Related')
mongo.connect(process.env.Pass,{useNewUrlParser:true}).then(console.log('db is conncted'))
const port = process.env.PORT || 5001; // Use environment variable or port 5001


app.use('/get',GetInfo)
app.use('/post',PostInfo)
app.use('/delete',DeleteInfo)
app.use('/login',Login)
app.use('/signup',Signup)
app.use('/post',PostSkill)
app.use('/get',GetSkill)
app.use('/delete',DeleteSkill)
app.use('/delete',DeletePortfolio)
app.use('/post',Portfolio)
app.use('/get',getPortfolio)
app.use('/post',Post)
app.use('/get',GetContent)
app.use('/edit',EditContent)
app.use("/post",PostContent)
app.use("/delete",DeleteContent)
app.use('/get',Get)
app.use('/get',Detail)
app.use('/related',Related)
app.use("/mail",Mail)

app.listen(5000,(req,res)=>{
    console.log(`The port is working now ${port}`)
})